cloudinary:
  api-key: 175631491224487
  api-secret: TmeGg3OGrfTjPGmY4Wj9cBnNYy8
  cloud-name: dzjoxccho
server:
  port: 8383
  error:
    include-message: always

spring:
  application:
    name: fashion-store
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/fashion-store
      auto-index-creation: true
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: phancongtu25032002@gmail.com
    password: skttvipvxzdjhezr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
mail:
  smtp:
    debug: true
jwt:
  secret: 1FE05E1FA7968F51E4A20A127CC2A16881CB909CD1A75C57C1A96C151C2B42AB
